title: DiscreteTom's Blog
root: posts # 选择`content`文件夹下的一个文件或目录作为`/`路径的页面
defaultLanguage: en # 文件后缀没有指明语言时默认使用的语言
repo: 'https://github.com/DiscreteTom/discretetom.github.io' # github repo address
email: 'discrete_tom@outlook.com' # author email address
author: 'DiscreteTom' # author github username
folderIcon: mdi-folder-outline # mdi icon name
fileIcon: mdi-file # mdi icon name
orderDecider: '@' # 用来确定内容顺序
headScripts: # to append custom scripts
  - src: https://www.googletagmanager.com/gtag/js?id=UA-137885294-1
    async: true
  - innerHTML: |
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-137885294-1');
friends:
  - title: 卡拉搜索/kalasearch
    url: https://kalasearch.cn/
    description: 托管的站内搜索引擎服务
friendsIcon: mdi-open-in-new