# powered by qiubaiying.github.io

# Site settings
title: DiscreteTom's Blog
SEOTitle: DiscreteTom's Blog
# header-img: img/header.png
email: discrete_tom@outlook.com
# description: ""
keyword: "Blog, DiscreteTom"
url: "http://discretetom.github.io"
# baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/DiscreteTom/DiscreteTom.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
github_username: DiscreteTom
# facebook_username: 
# jianshu_username:  
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
# paginate: 5 # 5 posts per page




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: true
    block:
      line_numbers: true
      start_line: 1




# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: DiscreteTom

# Gitalk
gitalk:
  enable: true #是否开启Gitalk评论
  clientID: 49812602cf60b16271f0 # from github application
  clientSecret: 3819ce44d536cc44b135543e581eac2ec6f3910f # from github application
  repo: discretetom.github.io
  owner: DiscreteTom
  admin: DiscreteTom
  distractionFreeMode: false #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: 

# Google Analytics
ga_track_id: 'UA-137885294-1'            # Format: UA-xxxxxx-xx
ga_domain: auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


collections:
  AlgorithmDesignAndAnalyze:
    output: true
    title: 算法设计与分析
  ComputerNetwork:
    output: true
    title: 计算机网络
  ComputerOrganizationPrinciple:
    output: true
    title: 计算机组成原理
  FormalLanguageAndAutomata:
    output: true
    title: 形式语言与自动机
  FundamentalsOfCompiling:
    output: true
    title: 编译原理
  MicrocomputerPrincipleAndInterfaceTechnology:
    output: true
    title: 微机原理与接口技术
  NaturalLanguageProcessing:
    output: true
    title: 自然语言处理
  OperatingSystem:
    output: true
    title: 操作系统
  PrinciplesOfCommunications:
    output: true
    title: 通信原理
  VHDL:
    output: true
    title: VHDL硬件编程


# Friends
# friends: [
#     {
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
